### PR TITLE
Adds support for configuration files in the scheduler

### PR DESCRIPTION
**Pull request by neithanmo**
this is how the config file looks like:
```
[scheduler]
address = "127.0.0.1:9000"

[[tasks_settings]]
exec_time = 60
memory = 2
devices = [0, 1, 2]
task_type = "MerkleProof"

[[tasks_settings]]
exec_time = 60
memory = 2
devices = [0, 1, 2]
task_type = "WindowPost"

[[tasks_settings]]
exec_time = 60
memory = 2
devices = [0, 1, 2]
task_type = "WinningPost"
```

### CODE REVIEW

**Comment by jleni** [comment]
Looks nice.
I wonder if we can use some structured name for devices instead of just a number.
Example

`devices = [ /nvidia/gpu/0, /nvidia/gpu/1 ]`

something in the form

`/{brand}/{type}/{index}`

**Comment by neithanmo** [comment]
> `devices = [ /nvidia/gpu/0, /nvidia/gpu/1 ]`

I discussed this with @leongb the other day. We agree that using raw numbers is not as user-friendly as we want. but so far, We do not have a tool for mapping devices' names (which are collision prone) to a unique id. or as you propose using /dev/gpu0, /dev/gpu1, or similar.

**Comment by leongb** [comment]
> > `devices = [ /nvidia/gpu/0, /nvidia/gpu/1 ]`
> 
> I discussed this with @leongb the other day. We agree that using raw numbers is not as user-friendly as we want. but so far, We do not have a tool for mapping devices' names (which are collision prone) to a unique id. or as you propose using /dev/gpu0, /dev/gpu1, or similar.

Wouldn't it be possible to make a serializer that takes (string?) "/nvidia/gpu/0" and maps that to a unique device ID? i assume the "0" is the unique thing in the string as well

**Comment by jleni** [comment]
I suppose Natanael means that we can do this in another PR.
But yes, using a serilizer is what I meant. And also the other two elements
would be important so we can differentiate between device types and brands
(example.. if we have two boards amd+nvidia.. which one is 0 and 1?)
We definitely need this URL structure in M2

**Review by leongb — APPROVED** [review]

**Pull request merged**
